name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟
  workflow_dispatch:        # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GT }}  # 你的 Personal Access Token
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "acncoder@gmail.com"

      - name: Add upstream & fetch
        run: |
          git remote | grep upstream || git remote add upstream https://github.com/ThatCoders/thatcoders.github.io.git
          git fetch upstream

      - name: Merge upstream/master into main
        run: |
          git checkout main
          git merge upstream/master --allow-unrelated-histories || echo "No changes to merge"

      - name: Push changes to origin
        run: |
          git push origin main
