name: Sync Fork with Upstream

on:
  # 每 10 分钟同步一次
  schedule:
    - cron: '*/10 * * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork default branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GT }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "acncoder@gmail.com"

      - name: Add upstream and fetch
        run: |
          # 添加 upstream，如果未添加过
          git remote | grep upstream || git remote add upstream https://github.com/ThatCoders/thatcoders.github.io.git
          git fetch upstream

      - name: Merge upstream default branch into fork default branch
        run: |
          # 获取你自己仓库的默认分支名
          MY_BRANCH="${{ github.event.repository.default_branch }}"
          
          # 获取 upstream 的默认分支名（通过 GitHub API）
          UPSTREAM_REPO="ThatCoders/thatcoders.github.io"
          UPSTREAM_BRANCH=$(curl -s https://api.github.com/repos/${UPSTREAM_REPO} | jq -r .default_branch)

          echo "Fork default branch: $MY_BRANCH"
          echo "Upstream default branch: $UPSTREAM_BRANCH"

          git checkout "$MY_BRANCH"
          git merge "upstream/$UPSTREAM_BRANCH" --allow-unrelated-histories || echo "Nothing to merge"

      - name: Push changes to your fork
        run: |
          git push origin "${{ github.event.repository.default_branch }}"
